stages:
  axes:
    cmd: "python ${paths.stages.axes}"
    deps:
      - "${paths.stages.axes}"
      - "${paths.config}/axes.yaml"
      - "${paths.models}"
    outs:
      - "${paths.axes}"

  runs:
    cmd: "python ${paths.stages.runs}"
    deps:
      - "${paths.stages.runs}"
      - "${paths.axes}"
      - "${paths.trials}"
    outs:
      - "${paths.runs}"
    params:
      - "records_to_average"

  parse_benchmarks:
    cmd: "python ${paths.stages.parse_benchmarks}"
    deps:
      - "${paths.stages.parse_benchmarks}"
      - "${paths.axes}"
      - "${paths.benchmarks}"
    outs:
      - "${paths.benchmarks_parsed}"

  pipeline:
    cmd: "python ${paths.stages.pipeline}"
    deps:
      - "${paths.stages.pipeline}"
      - "${paths.model_functions}"
      - "${paths.runs}"
      - "${paths.benchmarks_parsed}"
      - "${paths.validation}"
    outs:
      - "${paths.results}"

  metrics:
    cmd: "ploomber-engine ${paths.stages.metrics} NUL"
    deps:
      - "${paths.stages.metrics}"
      - "${paths.results}"
    metrics:
      - "${paths.file_pipeline_metrics}"
    plots:
      - "${paths.plot_new_fit_0}"
      - "${paths.plot_new_fit_1}"
      - "${paths.plot_new_fit_2}"
      - "${paths.plot_error_T_s}"
      - "${paths.plot_error_q_s}"
      - "${paths.plot_error_h_a}"
    params:
      - "do_plot"

  literature:
    cmd: "python ${paths.stages.literature}"
    deps:
      - "${paths.stages.literature}"
      - "${paths.literature}"
      - "${paths.models}"
    outs:
      - "${paths.literature_results}"

  originlab:
    cmd: "python ${paths.stages.originlab}"
    deps:
      - "${paths.stages.originlab}"
      - "${paths.results}"
      - "${paths.literature_results}"
      - "${paths.plotter}"
    outs:
      - "${paths.originlab_results}"
    plots:
      - "${paths.originlab_plot_files.lit}"
      - "${paths.originlab_plot_files.low}"
