do_plot: true
records_to_average: 9
paths:
  project: .
  data: data
  propshop: data/propshop
  package: src/boilerdata
  axes_enum: src/boilerdata/axes_enum.py
  models: src/boilerdata/models
  stages:
    axes: src/boilerdata/stages/axes.py
    literature: src/boilerdata/stages/literature.py
    metrics: src/boilerdata/stages/metrics.ipynb
    originlab: src/boilerdata/stages/originlab.py
    parse_benchmarks: src/boilerdata/stages/parse_benchmarks.py
    pipeline: src/boilerdata/stages/pipeline.py
    runs: src/boilerdata/stages/runs.py
  validation: src/boilerdata/validation.py
  config: data/config
  axes_config: data/config/axes.yaml
  trials_config: data/config/trials.yaml
  plot_config: data/config/plotting
  mpl_base: data/config/plotting/base.mplstyle
  mpl_hide_title: data/config/plotting/hide_title.mplstyle
  model: data/model.dillpickle
  benchmarks: data/benchmarks
  axes: data/axes
  axes_enum_copy: data/axes/axes_enum.py
  file_originlab_coldes: data/axes/originlab_coldes.txt
  literature: data/literature
  plotter: data/plotter
  file_plotter: data/plotter/results.opju
  trials: data/curves
  benchmarks_parsed: data/benchmarks_parsed
  file_benchmarks_parsed: data/benchmarks_parsed/benchmarks_parsed.csv
  literature_results: data/literature_results
  file_literature_results: data/literature_results/lit.csv
  originlab_plots: data/originlab_plots
  originlab_plot_files:
    lit: data/originlab_plots/lit.png
    low: data/originlab_plots/low.png
  originlab_results: data/originlab_results
  file_originlab_results: data/originlab_results/originlab_results.csv
  plots: data/plots
  plot_new_fit_0: data/plots/new_fit_0.png
  plot_new_fit_1: data/plots/new_fit_1.png
  plot_new_fit_2: data/plots/new_fit_2.png
  plot_error_T_s: data/plots/error_T_s.png
  plot_error_q_s: data/plots/error_q_s.png
  plot_error_h_a: data/plots/error_h_a.png
  results: data/results
  file_results: data/results/results.csv
  runs: data/runs
  file_runs: data/runs/runs.csv
  tables: data/tables
  file_pipeline_metrics: data/tables/pipeline_metrics.json
